package org.androidorm.annotations;

import java.lang.annotation.Retention;

import static java.lang.annotation.RetentionPolicy.RUNTIME;

/**
 * Indicating that id column should be autogenerated by database. Use only wit {@link Id} annotation
 */
@Retention(RUNTIME)
public @interface GeneratedValue {

}
