package org.androidorm.annotations.column;

import org.androidorm.accessors.DbAccessor;
import org.androidorm.annotations.Applier;
import org.androidorm.annotations.GeneratedValue;
import org.androidorm.exceptions.MappingException;
import org.androidorm.types.DbType;
import org.androidorm.types.SimpleType;

/**
 * Apply GeneratedValue annotation to accessor.
 */
public class GeneratedValueApplier extends Applier<DbAccessor, GeneratedValue> {

    @Override
    public void apply(DbAccessor accessor, GeneratedValue annotation) throws MappingException {
        SimpleType simpleType = SimpleType.convert(accessor.getRealType());
        if (simpleType == null || simpleType.getDbType() != DbType.INTEGER) {
            throw new MappingException("AUTOINCREMENT allowed only for INTEGER columns");
        }

        accessor.setAutogenerated(true);
    }

    @Override
    public Class<GeneratedValue> getAnnotationType() {
        return GeneratedValue.class;
    }
}
